apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: default
  labels:
    app: analytics-service
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: hemantbarole/url-analytics-service:REPLACE_ME
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/

            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://adminAnal:qwertyPWD@analytic-db:27018/analytic_DB?authSource=admin

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: analytics-group
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
              value: org.apache.kafka.common.serialization.StringDeserializer
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              value: org.springframework.kafka.support.serializer.JsonDeserializer
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE
              value: com.tp.main.dto.ClickEvent
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES
              value: "*"
            - name: SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL
              value: "false"

            - name: INTERNAL_SECRET
              value: my-super-secret-key

            - name: SPRING_LAZY_INITIALIZATION
              value: "false"
            - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
              value: "30"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "15"
            
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx160m -XX:+UseSerialGC -Xss512k -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          resources:
            requests:
              memory: "150Mi"
              cpu: "40m"
            limits:
              memory: "280Mi"
              cpu: "250m"
          # STARTUP PROBE: Gives your app up to 2 minutes to boot on your 8GB laptop
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9091
            failureThreshold: 30
            periodSeconds: 5

          # LIVENESS PROBE: Runs continuously after startup passes
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9091
            periodSeconds: 10
            timeoutSeconds: 2
          
          # READINESS PROBE: Controls traffic routing
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9091
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP