apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: hemantbarole/url-discovery-service:REPLACE_ME
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_LAZY_INITIALIZATION
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx160m -XX:+UseSerialGC -Xss512k -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          resources:
            requests:
              memory: "180Mi"
              cpu: "50m"
            limits:
              memory: "320Mi"
              cpu: "300m"
          # STARTUP PROBE: Gives your app up to 2 minutes to boot on your 8GB laptop
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            failureThreshold: 30
            periodSeconds: 5

          # LIVENESS PROBE: Runs continuously after startup passes
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            periodSeconds: 10
            timeoutSeconds: 2
          
          # READINESS PROBE: Controls traffic routing
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP