apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
  namespace: default
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: hemantbarole/url-security-service:latest
          ports:
            - containerPort: 9099
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/

            - name: INTERNAL_SECRET
              value: my-super-secret-key
            - name: SPRING_LAZY_INITIALIZATION
              value: "false"
            
            - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
              value: "30"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "15"
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx128m"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          resources:
            limits:
              memory: "320Mi"
              cpu: "400m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          # STARTUP PROBE: Gives your app up to 2 minutes to boot on your 8GB laptop
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9099
            failureThreshold: 24
            periodSeconds: 5

          # LIVENESS PROBE: Runs continuously after startup passes
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9099
            periodSeconds: 10
            timeoutSeconds: 2
          
          # READINESS PROBE: Controls traffic routing
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9099
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: default
spec:
  selector:
    app: security-service
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9099
  type: ClusterIP