services:
  # ---------------- 1. Infrastructure: Service-Registry ------------------------------
  discovery-service:
    image: hemantbarole/url-discovery-service:latest
    build: 
      context: ./Backend/DiscoveryService
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8761:8761"
    environment:
      - spring_profiles_active=docker
      - SPRING_MAIN_LAZY_INITILIZATION=true
      - EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS=60000
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s
    networks:
      - url-shortener-net
  
  # ---------------- 2. Infrastructure: Redis (Pre-built image) ------------------------------
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - url-shortener-net

  # ---------------- 3. Infrastructure: Message Broker (Zookeeper + kafka) ------------------------------    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Xmx64M -Xms64M"
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: 'ruok'
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/2181' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    networks:
      - url-shortener-net
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Xmx256M -Xms128M"
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      # test: ["CMD", "kafka-topics", "--bootstrap-server", "127.0.0.1:29092", "--list"]
      test: ["CMD-SHELL", "nc -z localhost 29092 || exit 1"] # Ultra-lightweight healthcheck that doesn't trigger a new Java process spike
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - url-shortener-net
  
  # ---------------- 4. Infrastructure: Normal JWT Authentication Flow ------------------------------
  security-service:
    image: hemantbarole/url-security-service:latest
    build: 
      context: ./Backend/SecurityService
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9099:9099"
    environment:
      - spring_profiles_active=docker
      - eureka_client_serviceUrl_defaultZone=http://discovery-service:8761/eureka/

      - INTERNAL_SECRET=my-super-secret-key
      - SPRING_MAIN_LAZY_INITIALIZATION=true
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=30     # Fetch every 30s instead of 5s
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=15 # Heartbeat every 15s instead of 5s
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      discovery-service:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    networks:
      - url-shortener-net

  # ---------------- 5. Infrastructure: Core Service:- APIGateway-Service ------------------------------  
  apigateway-service:
    image: hemantbarole/url-apigateway-service:latest
    build: 
      context: ./Backend/APIGateway
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9096:9096"
    environment:
      - spring_profiles_active=docker
      - eureka_client_serviceUrl_defaultZone=http://discovery-service:8761/eureka/

      - spring_data_redis_host=redis
      - spring_data_redis_port=6379

      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=200566460056-qlkqa2crgiottbur2dg8k5geq2fjn04q.apps.googleusercontent.com
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=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
      
      - APP_SECURITY_INTERNAL_HANDSHAKE_SECRET=my-super-secret-key
      - SPRING_MAIN_LAZY_INITIALIZATION=true
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=30     # Fetch every 30s instead of 5s
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=15 # Heartbeat every 15s instead of 5s
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dio.netty.resolver.dns.defaultAddressTypes=IPV4_ONLY -Dsun.net.spi.nameservice.provider.1=dns,sun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9096/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    depends_on:
      discovery-service:
        condition: service_healthy
      security-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - url-shortener-net

  # ---------------- 6. Business Logic: Other-Service ------------------------------    
  # ---------------- Key-Generation-Service ------------------------------    
  kgs-db:
    image: mysql:8.0
    container_name: kgs-db
    environment:
      - MYSQL_DATABASE=kgs_DB
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=kgsUser
      - MYSQL_PASSWORD=kgsPass
    ports:
      - "3306:3306"
    volumes:
      - kgs-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - url-shortener-net
  
  kgs:
    image: hemantbarole/url-key-generation:latest
    build: 
      context: ./Backend/KeyGeneration
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9097:9097"
    environment:
      - spring_profiles_active=docker
      - eureka_client_serviceUrl_defaultZone=http://discovery-service:8761/eureka/

      - SPRING_DATASOURCE_URL=jdbc:mysql://kgs-db:3306/kgs_DB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      
      - FLYWAY_ENABLED=true
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - INTERNAL_SECRET=my-super-secret-key

      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=200566460056-qlkqa2crgiottbur2dg8k5geq2fjn04q.apps.googleusercontent.com
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=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
      
      - SPRING_MAIN_LAZY_INITIALIZATION=true
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=30     # Fetch every 30s instead of 5s
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=15 # Heartbeat every 15s instead of 5s
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      kgs-db:
        condition: service_started
      redis:
        condition: service_started
      security-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9097/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    networks:
      - url-shortener-net
# ------------------------ Key-Generation-Service End -----------------------------------
  
  # ---------------- Url-Service ------------------------------    
  url-db:
    image: mongo:latest
    container_name: url-db
    # command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: url_DB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    ports:
      - "27017:27017"
    volumes:
      - url-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "qwerty", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - url-shortener-net

  url-service:
    image: hemantbarole/url-urlservice:latest
    build: 
      context: ./Backend/URLService
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9094:9094"
    environment:
      - spring_profiles_active=docker
      - eureka_client_serviceUrl_defaultZone=http://discovery-service:8761/eureka/

      - spring_data_redis_host=redis
      - spring_data_redis_port=6379

      - SPRING_DATA_MONGODB_URI=mongodb://admin:qwerty@url-db:27017/url_DB?authSource=admin

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_KAFKA_PRODUCER_KEY_SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER=org.springframework.kafka.support.serializer.JsonSerializer
      - SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS=false

      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=200566460056-qlkqa2crgiottbur2dg8k5geq2fjn04q.apps.googleusercontent.com
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=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
      - INTERNAL_SECRET=my-super-secret-key

      - SPRING_MAIN_LAZY_INITIALIZATION=true
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=30     # Fetch every 30s instead of 5s
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=15 # Heartbeat every 15s instead of 5s
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      url-db:
        condition: service_started
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      security-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9094/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    networks:
      - url-shortener-net
# ------------------------ Url-Service End -----------------------------------

  analytic-db:
    image: mongo:latest
    container_name: analytic-db
    # command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: analytic_DB
      MONGO_INITDB_ROOT_USERNAME: adminAnal
      MONGO_INITDB_ROOT_PASSWORD: qwertyPWD
    ports:
      - "27018:27017"
    volumes:
      - analytic-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "adminAnal", "-p", "qwertyPWD", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - url-shortener-net

  # ---------------- Analytics-Service ------------------------------    
  analytics-service:
    image: hemantbarole/url-analytics-service:latest
    build: 
      context: ./Backend/AnalyticsService
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9091:9091"
    environment:
      - spring_profiles_active=docker
      - eureka_client_serviceUrl_defaultZone=http://discovery-service:8761/eureka/

      - SPRING_DATA_MONGODB_URI=mongodb://adminAnal:qwertyPWD@analytic-db:27017/analytic_DB?authSource=admin
      
      - spring_data_redis_host=redis
      - spring_data_redis_port=6379

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=analytics-group
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER=org.springframework.kafka.support.serializer.JsonDeserializer
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE="com.tp.main.dto.ClickEvent"
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES="*"
      - SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL=false

      # - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=200566460056-qlkqa2crgiottbur2dg8k5geq2fjn04q.apps.googleusercontent.com
      # - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=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
      - INTERNAL_SECRET=my-super-secret-key
      
      - SPRING_MAIN_LAZY_INITIALIZATION=false
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=30     # Fetch every 30s instead of 5s
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=15 # Heartbeat every 15s instead of 5s
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    depends_on:
      analytic-db:
        condition: service_started
      kafka:
        condition: service_healthy
      security-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - url-shortener-net
# ------------------------ Analytic-Service End -----------------------------------

  # ---------------- User-Service ------------------------------    
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      - MYSQL_DATABASE=userUrl_DB
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=authUser
      - MYSQL_PASSWORD=authPass
    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - url-shortener-net
  
  user-service:
    image: hemantbarole/url-user-service:latest
    build: 
      context: ./Backend/UserService
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9098:9098"
    environment:
      - spring_profiles_active=docker
      - eureka_client_serviceUrl_defaultZone=http://discovery-service:8761/eureka/

      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/userUrl_DB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect

      - SPRING_MAIN_LAZY_INITIALIZATION=true
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=30     # Fetch every 30s instead of 5s
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=15 # Heartbeat every 15s instead of 5s
      - JAVA_OPTS=-Xms64m -Xmx128m
      - JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      user-db:
        condition: service_started
      security-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9098/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    networks:
      - url-shortener-net
# ------------------------ User-Service End -----------------------------------

  # ---------------- 7. Frontend: React Application------------------------------    
  frontend:
    image: hemantbarole/url-shortener-ui:latest
    build: 
      context: ./Frontend/url-shortener-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
     - REACT_APP_API_BASE_URL=http://localhost:9096
    depends_on:
      apigateway-service:
        condition: service_started
    networks:
      - url-shortener-net

# ------------------ This tell docker to create persistent storage on host machine --------------------
volumes:
  user-db-data:
  analytic-db-data:
  url-db-data:
  kgs-db-data:
  redis-data:
  kafka_data:

networks:
  url-shortener-net:
    driver: bridge