apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hemant15-Bl/Url-Shortener.git' # <-- repo URL
    targetRevision: main
    path: argocd-apps # <-- The folder ArgoCD will watch
  destination:
    server: 'https://kubernetes.default.svc' # Deploys directly to your running cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true     # Automatically deletes resources in k8s if you delete them from Git
      selfHeal: true  # Automatically fixes changes if someone manually tampers with kubectl