apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Reserves 1GB of disk space for Kafka messages
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
          env:
            # Kraft mode configuration
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            # Networking Listeners
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            
            # Resource Adjustments & Optimization
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: "-Xmx256M -Xms128M"
            # Tells Kafka exactly where to write its persistent logs inside the container
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTg0NDM0Rk"
          resources:
            limits:
              memory: "384Mi"
              cpu: "400m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          # EFFICIENT NETWORK HEALTH CHECK
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30 # Gives Kafka time to connect to Zookeeper
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 15
          # 1. Mount the volume inside the container path
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
      # 2. Link the volume to the PVC declared at the top of the file
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP