apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-db-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-db
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
      matchLabels:
        app: url-db
  template:
    metadata:
      labels:
        app: url-db
    spec:
      containers:
        - name: url-db
          image: mongo:latest
          args:
            - "--wiredTigerCacheSizeGB=0.25" # Increased to Mongo's hard minimum floor
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: url_DB
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: qwerty
          resources:
            requests:
              memory: "192Mi"
              cpu: "150m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          # NATIVE MONGO HEALTH CHECK
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --username
                - admin
                - --password
                - qwerty
                - --authenticationDatabase
                - admin
                - --eval
                - "db.adminCommand({ ping: 1 })"
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: url-db-storage
              mountPath: /data/db
      volumes:
        - name: url-db-storage
          persistentVolumeClaim:
            claimName: url-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: url-db
  namespace: default
spec:
  selector:
    app: url-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP