spring:
  application:
    name: KEY-GENERATION

  datasource:
    url: jdbc:mysql://localhost:3306/kgs_DB
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 200566460056-qlkqa2crgiottbur2dg8k5geq2fjn04q.apps.googleusercontent.com
            client-secret: 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

server:
  port: 9097

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

internal:
  secret: my-super-secret-key

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always