apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hemant15-Bl/Url-Shortener.git' # <-- Your repo URL
    targetRevision: main
    path: k8s/infra # <-- Points to your infrastructure folder
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true     # Safer to keep false for infra to prevent accidental data deletion
      selfHeal: true   # Keeps configurations synced if manual tweaks happen