spring:
  application:
    name: DISCOVERY-SERVICE

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: DISCOVERY-SERVICE # if running local machine then 'localhost''
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always